---
root: true
overrides:
- files:
  - "*.ts"
  env:
    browser: true
    es6: true
    node: true
  extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  parser: "@typescript-eslint/parser"
  parserOptions:
    project: tsconfig.json
    sourceType: module
  plugins:
  - "@angular-eslint/eslint-plugin"
  - "@typescript-eslint"
  - unused-imports
  - import
  rules:
    "@angular-eslint/component-class-suffix": error
    "@angular-eslint/directive-class-suffix": 'off'
    "@angular-eslint/no-host-metadata-property": error
    "@angular-eslint/no-input-rename": error
    "@angular-eslint/no-inputs-metadata-property": error
    "@angular-eslint/no-output-on-prefix": error
    "@angular-eslint/no-output-rename": error
    "@angular-eslint/no-outputs-metadata-property": error
    "@angular-eslint/use-lifecycle-interface": error
    "@angular-eslint/use-pipe-transform-interface": error
    "@typescript-eslint/explicit-module-boundary-types": 'off'
    "@typescript-eslint/adjacent-overload-signatures": error
    "@typescript-eslint/array-type": 'off'
    "@typescript-eslint/ban-types":
    - error
    - types:
        "{}": false
        object: false
      extendDefaults: true
    "@typescript-eslint/consistent-type-assertions": error
    "@typescript-eslint/consistent-type-definitions": error
    "@typescript-eslint/dot-notation": 'off'
    "@typescript-eslint/explicit-member-accessibility":
    - 'off'
    - accessibility: explicit
    "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
    "@typescript-eslint/naming-convention": 'off'
    "@typescript-eslint/no-empty-function": 'off'
    "@typescript-eslint/no-empty-interface": error
    "@typescript-eslint/ban-ts-comment": 'off'
    "@typescript-eslint/no-explicit-any": 'off'
    "@typescript-eslint/no-inferrable-types":
    - error
    - ignoreParameters: true
    "@typescript-eslint/no-misused-new": error
    "@typescript-eslint/no-namespace": error
    "@typescript-eslint/no-non-null-assertion": error
    "@typescript-eslint/no-parameter-properties": 'off'
    "@typescript-eslint/no-shadow":
    - 'off'
    - hoist: all
    "@typescript-eslint/no-unused-expressions": error
    "@typescript-eslint/no-var-requires": 'off'
    "@typescript-eslint/prefer-for-of": error
    "@typescript-eslint/prefer-function-type": error
    "@typescript-eslint/prefer-namespace-keyword": error
    "@typescript-eslint/prefer-regexp-exec": 'off'
    "@typescript-eslint/type-annotation-spacing": error
    "@typescript-eslint/unified-signatures": error
    "@typescript-eslint/no-unsafe-argument": 'off'
    "@typescript-eslint/no-unsafe-call": 'off'
    "@typescript-eslint/no-unsafe-member-access": 'off'
    "@typescript-eslint/no-unsafe-assignment": 'off'
    "@typescript-eslint/no-unsafe-return": 'off'
    "@typescript-eslint/no-use-before-define": 'off'
    "@typescript-eslint/no-floating-promises": 'off'
    "@typescript-eslint/no-unnecessary-type-assertion": 'off'
    "@typescript-eslint/unbound-method": 'off'
    "@typescript-eslint/restrict-plus-operands": 'off'
    "@typescript-eslint/no-unused-vars": 'off'
    "@typescript-eslint/restrict-template-expressions": 'off'
    no-prototype-builtins: 'off'
    no-useless-escape: 'off'
    no-irregular-whitespace: 'off'
    arrow-parens:
    - 'off'
    - always
    complexity: 'off'
    constructor-super: error
    curly: error
    eol-last: error
    eqeqeq:
    - error
    - smart
    guard-for-in: error
    id-match: error
    max-classes-per-file: 'off'
    new-parens: error
    no-bitwise: error
    no-caller: error
    no-cond-assign: error
    no-console:
    - error
    - allow:
      - log
      - dirxml
      - warn
      - error
      - dir
      - timeLog
      - assert
      - clear
      - count
      - countReset
      - group
      - groupCollapsed
      - groupEnd
      - table
      - Console
      - markTimeline
      - profile
      - profileEnd
      - timeline
      - timelineEnd
      - timeStamp
      - context
    no-debugger: error
    no-empty: 'off'
    no-eval: error
    no-fallthrough: error
    no-invalid-this: 'off'
    no-multiple-empty-lines: 'off'
    no-new-wrappers: error
    no-restricted-imports:
    - error
    - rxjs/Rx
    no-throw-literal: error
    no-unsafe-optional-chaining: 'off'
    no-trailing-spaces: error
    no-undef-init: error
    no-unsafe-finally: error
    no-unused-labels: error
    no-var: error
    object-shorthand: error
    one-var:
    - error
    - never
    prefer-const: error
    quote-props:
    - error
    - as-needed
    radix: error
    space-before-function-paren:
    - error
    - anonymous: always
      asyncArrow: always
      named: never
    spaced-comment:
    - error
    - always
    - exceptions:
      - "*"
      markers:
      - "/"
    use-isnan: error
    valid-typeof: 'off'
    unused-imports/no-unused-imports: warn
  settings:
    import/resolver:
      typescript:
        project: './tsconfig.json'
- files:
  - "*.component.ts"
  extends:
  - plugin:@angular-eslint/template/process-inline-templates
  parser: "@typescript-eslint/parser"
  parserOptions:
    project: tsconfig.json
    sourceType: module
  plugins:
    - change-detection-strategy
  rules:
    "@angular-eslint/directive-selector":
    - error
    - type: "attribute"
      prefix: "sv"
      style: "camelCase"
    "@angular-eslint/component-selector":
    - error
    - type: "element"
      prefix: "sv"
      style: "kebab-case"
    "change-detection-strategy/on-push": error
- files:
  - "*.component.html"
  extends:
  - plugin:@angular-eslint/template/recommended
  rules:
    "@angular-eslint/template/eqeqeq":
      - error
      - allowNullOrUndefined: true
    "@angular-eslint/template/no-call-expression":
      - error
